title: Repleatur
email: veronica@repleatur.net
description: > # this means to ignore newlines until "baseurl:"
  Choir-related things for Latin Masses in the Parramatta diocese.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.repleatur.net" # the base hostname & protocol for your site
#url: "http://localhost:4000"

# Google analytics
google_analytics: UA-39810569-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: repleatur

# Social icons
show_social_icons: true
github_username: veromary
stackoverflow_id:
twitter_username: repleatur
google_plus_id: 
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button: 
feed: http://feeds.feedburner.com/Repleatur

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
#=======
#title:       Pixyll
#email:       your_email@example.com
#author:      John Otander
#description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
#baseurl:     ""
#url:         "http://pixyll.com"

# Google analytics
#google_analytics:

# Optional features
#animated:           false
#show_related_posts: false
#show_post_footers:  false
#show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
#disqus_shortname:

# Social icons
#github_username:
#bitbucket_username:
#stackoverflow_id:
#twitter_username:
#google_plus_id:
#linkedin_username:
#angellist_username:
#medium_id:
#bitcoin_url:
#paypal_url:
#flattr_button:

# Post sharing icons
#show_sharing_icons: false
#share_text: 'Share this post!'
# Change to 'true' to enable individual icons
#share_facebook: false
#share_twitter: false
#share_googleplus: false
#>>>>>>> 17093accf3ed12e81ce160b38ede5bdc95c27744
#share_linkedin: false
#share_digg: false
#share_tumblr: false
#share_reddit: false
#share_stumbleupon: false
#<<<<<<< HEAD

# Build settings
markdown:  kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title/
paginate:     10
sass:
  compressed: true
#gems: ['jekyll-lunr-js-search']
#lunr_search:
#  excludes: [rss.xml, atom.xml, feed.xml]
#lunr_search:
#  stopwords: "stopwords.txt"
#=======
#share_hackernews: false

# Build settings
#markdown:     kramdown
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
#permalink:    pretty
#paginate:     4
#sass:
#  compressed: true
gems:
 - jekyll-sitemap
 - jekyll-paginate
#>>>>>>> 17093accf3ed12e81ce160b38ede5bdc95c27744
