# Site settings
title: Repleatur
email: veronica@repleatur.net
description: > # this means to ignore newlines until "baseurl:"
  Choir-related things for Latin Masses in the Parramatta diocese.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.repleatur.net" # the base hostname & protocol for your site
#url: "http://localhost:4000"

# Google analytics
google_analytics: UA-39810569-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: repleatur

# Social icons
show_social_icons: true
github_username: veromary
stackoverflow_id:
twitter_username: repleatur
google_plus_id: 
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button: 
feed: http://feeds.feedburner.com/Repleatur

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title/
paginate:     10
sass:
  compressed: true
gems: ['jekyll-lunr-js-search']
lunr_search:
  excludes: [rss.xml, atom.xml, feed.xml]
  min_length: 4
